version: "3.9"

services:
  e2e:
    build: .
    image: mv3-e2e:latest
    environment:
      - CI=true
    volumes:
      - ./:/app
      - ./playwright-report:/app/playwright-report
    working_dir: /app
    command: npm run test:e2e
    shm_size: 2gb
